services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - cadt-express
      
    environment:
      - EXPRESS_HOST_1=idg-03-cadt-express-1 
      - EXPRESS_HOST_2=idg-03-cadt-express-2
      - EXPRESS_HOST_3=idg-03-cadt-express-3
      - EXPRESS_HOST_4=idg-03-cadt-express-4
      - EXPRESS_HOST_5=idg-03-cadt-express-5
      - EXPRESS_PORT=3000
      - NGINX_SERVER_NAME=localhost
      - NGINX_MAX_BODY=100M
    ports:
      - "3000:3000"
  cadt-express:
    build:
      context: .
      dockerfile: Dockerfile
   
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    scale: 5 # auto scale up to 5 instances server load
    depends_on:
      - cadt-db
  cadt-db:
    image: mongo:8.0.12-noble
    container_name: cadt-db
    ports:
      - "27017:27017"
    volumes:
      - cadt-db-data:/data/db
  cadt-redis-cache:
    image: redis:8.2.0-alpine
    container_name: cadt-redis-cache
    ports:
      - "6379:6379"
volumes:
  cadt-db-data: